import { Suspense } from "react";
import "./globals.css";
import LayoutClient from "./layoutclient";

export const metadata = {
  title: "UniTrack",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Suspense>
          <LayoutClient>{children}</LayoutClient>
        </Suspense>
      </body>
    </html>
  );
}
